version: '3.8'
networks: 
  application: 
    driver: bridge
    
services:

  fastapi-huggingface:
      image: fastapi-huggingface
      container_name: fastapi-huggingface
      build:
        context: ./
        dockerfile: ./Dockerfile
      ports:
        - 8081:80
      volumes:
        - ./src:/src
      networks: 
        - application
      command: bash -c "sleep 5s && uvicorn main:app --host 0.0.0.0 --port 80 --reload"